In [5]:
import os
import numpy as np
import matplotlib as plt
import pandas as pd
import torch

In [6]:
with open('poems_dataset.csv', 'r', encoding='utf-8') as f:
    csvFile = pd.read_csv(f)

dataset = csvFile.drop(columns=['id', 'url']).dropna(subset=['title'])
dataset.info()
dataset.head()

<class 'pandas.core.frame.DataFrame'>
Index: 107176 entries, 0 to 171187
Data columns (total 3 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   content  107176 non-null  object
 1   title    107176 non-null  object
 2   genre    107176 non-null  object
dtypes: object(3)
memory usage: 3.3+ MB

,content,title,genre
0,ngày đông se sắt lạnh trong lòng\ncó việc đi n...,SAY NẮNG,7 chu
2,tết có người vui có kẻ buồn\nngười cười toe to...,TẾT HAI THÁI CỰC,7 chu
3,đã quá ba mươi mộng lỡ làng\nđi tìm day dứt mả...,TRÁI NGANG ĐỨC HẠNH,7 chu
4,mai đào nở rộ đón nàng xuân\nsợi nắng hanh vàn...,DÁNG XUÂN,7 chu
5,giữa thảm xanh của những khu vườn\nmái ngói ng...,VIẾNG CHÙA HỘI PHƯỚC,7 chu

In [7]:
dataset.convert_dtypes(infer_objects=False)
dataset_7chu = dataset[dataset['genre'] == '7 chu'].drop(columns=['genre'])
dataset_7chu.info()
dataset_7chu.head()

<class 'pandas.core.frame.DataFrame'>
Index: 12315 entries, 0 to 171187
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   content  12315 non-null  object
 1   title    12315 non-null  object
dtypes: object(2)
memory usage: 288.6+ KB

                                             content                 title
0  ngày đông se sắt lạnh trong lòng\ncó việc đi n...              SAY NẮNG
2  tết có người vui có kẻ buồn\nngười cười toe to...      TẾT HAI THÁI CỰC
3  đã quá ba mươi mộng lỡ làng\nđi tìm day dứt mả...   TRÁI NGANG ĐỨC HẠNH
4  mai đào nở rộ đón nàng xuân\nsợi nắng hanh vàn...             DÁNG XUÂN
5  giữa thảm xanh của những khu vườn\nmái ngói ng...  VIẾNG CHÙA HỘI PHƯỚC

In [8]:
flattened_dataset_7chu = dataset_7chu[['title', 'content']].values.flatten()
with open('dataset_7chu.txt', 'w', encoding='utf-8') as file:
    index = 0 
    for value in flattened_dataset_7chu:
        file.write(f"{value}")
        if index % 2 == 0:
            file.write(':\n')
        else:
            file.write('\n\n')
        index += 1